### ISSUE TITLE
Correlation matrix

### ISSUE THREAD

**Issue by swvanderlaan** [jrs95/gassocplot#1]
Hi,

How do you go about creating a correlation matrix of the SNPs you want to plot?

Thanks!

Sander

**Comment by jrs95** [comment]
Hi Sander,

Firstly, I apologize for the delayed response. I have recently changed career path slightly and taken a job in industry, and I haven't been keeping as close an eye on my GitHub repositories as I would like. Secondly, I'm a big fan of your work!

I was planning on making an API to get an LD matrix from 1000G, but that is probably going to be unlikely now given my job move. Happily, however, there is now the LDlinkR package which queries the LDlink API. I believe the required function is LDmatrix. This matrix will then have to be square-rooted (as the gassocplot uses r not r2) and formatted such that the matrix matches the rows in the marker data frame, i.e. each row i in the markers data frame should correspond to row i and column i in the corr matrix creating missing values in the corr matrix if necessary.

If I have time, I may at some point write a wrapper for LDlink to be used with gassocplot. 

I hope this helps. 

Best wishes,

James

**Comment by swvanderlaan** [comment]
Hi James,

Many thanks for the reply - and in return apologies for my slow response. :-) 

I will check out your suggestion. 

Best,

Sander
