### ISSUE TITLE
How Do names of SNPs of interest (addition to top SNP) draw in the regional association plot?

### ISSUE THREAD

**Issue by kaanokay** [jrs95/gassocplot#3]
Hi,

Firstly, I want to thank you for this useful package.

I want to put the names of other SNPs rather than top SNP in the regional-association plot.

How can I do that using stack_assoc_plot() function in gassocplot package?

Thanks for helping.

Best.

**Comment by jrs95** [comment]
Hi Kaan,

I’m afraid only one point can be labelled at the moment. I am developing a new version with multi-label facility, but this won’t be available for a while.

Best wishes,

James

**Comment by kaanokay** [comment]
Hi James,

Thanks for your quick reply.

I am impatiently waiting for the new version.

Best.

**Comment by jrs95** [comment]
Hi @kaanokay,

[gassocplot2](https://github.com/jrs95/gassocplot2) is now available, which incorporates additional marker labelling.

Best wishes,

James

**Comment by kaanokay** [comment]
Hi @jrs95,

Thank you for this update. I'll use it in my research.

Best.
