### ISSUE TITLE
run"gassocplot::stack_assoc_plot" and the erro showed:object 'genetic_map' not found

### ISSUE THREAD

**Issue by lorenelovestudy** [jrs95/gassocplot#5]
hello,
when i run"gassocplot::stack_assoc_plot" and the erro showed:object 'genetic_map' not found. The following is my code:

temp <- coloc_to_gassocplot(out, plink_bin = "E:/lpq/phd/medelian/RC/rc/qtl/plink_win64_20230116/plink.exe",
  bfile = "E:/lpq/phd/medelian/RC/rc/qtl/g1000_eur/g1000_eur")

gassocplot::stack_assoc_plot(temp$markers, temp$z, 
                             temp$corr, traits=temp$traits)

Looking forward to your respond!Thanks!

**Comment by lorenelovestudy** [comment]
![image](https://github.com/jrs95/gassocplot/assets/127404255/1168da65-cc7b-41f5-86f5-a885479be32e)
Here is my temp data look like

**Comment by jrs95** [comment]
Hi,

First of all I would advise you to use [gassocplot2](https://github.com/jrs95/gassocplot2), as gassocplot is no longer maintained.

All you need to do is load the library, i.e. library(gassocplot).

Best wishes,

James
